src/Entity/Versus.php
<?php

namespace App\Entity;

use App\Repository\VersusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VersusRepository::class)]
class Versus
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'versuses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $gameid = null;

    #[ORM\ManyToOne(inversedBy: 'versuses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Team $team1 = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Team $team2 = null;

    #[ORM\Column]
    private ?float $rate_team1 = null;

    #[ORM\Column]
    private ?float $rate_team2 = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne]
    private ?Team $winner = null;

    #[ORM\OneToMany(mappedBy: 'versusid', targetEntity: Bet::class, orphanRemoval: true)]
    private Collection $bets;

    public function __construct()
    {
        $this->bets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameid(): ?Game
    {
        return $this->gameid;
    }

    public function setGameid(?Game $gameid): static
    {
        $this->gameid = $gameid;

        return $this;
    }

    public function getTeam1(): ?Team
    {
        return $this->team1;
    }

    public function setTeam1(?Team $team1): static
    {
        $this->team1 = $team1;

        return $this;
    }

    public function getTeam2(): ?Team
    {
        return $this->team2;
    }

    public function setTeam2(?Team $team2): static
    {
        $this->team2 = $team2;

        return $this;
    }

    public function getRateTeam1(): ?float
    {
        return $this->rate_team1;
    }

    public function setRateTeam1(float $rate_team1): static
    {
        $this->rate_team1 = $rate_team1;

        return $this;
    }

    public function getRateTeam2(): ?float
    {
        return $this->rate_team2;
    }

    public function setRateTeam2(float $rate_team2): static
    {
        $this->rate_team2 = $rate_team2;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getWinner(): ?Team
    {
        return $this->winner;
    }

    public function setWinner(?Team $winner): static
    {
        $this->winner = $winner;

        return $this;
    }

    /**
     * @return Collection<int, Bet>
     */
    public function getBets(): Collection
    {
        return $this->bets;
    }

    public function addBet(Bet $bet): static
    {
        if (!$this->bets->contains($bet)) {
            $this->bets->add($bet);
            $bet->setVersusid($this);
        }

        return $this;
    }

    public function removeBet(Bet $bet): static
    {
        if ($this->bets->removeElement($bet)) {
            // set the owning side to null (unless already changed)
            if ($bet->getVersusid() === $this) {
                $bet->setVersusid(null);
            }
        }

        return $this;
    }
}

src/Form/VersusType.php
<?php

namespace App\Form;

use App\Entity\Versus;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VersusType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rate_team1')
            ->add('rate_team2')
            ->add('description')
            ->add('date')
            ->add('gameid', EntityType::class, [
                'class' => 'App\Entity\Game',
                'choice_label' => 'game_name', // Assurez-vous que 'nom' est le nom du champ que vous souhaitez afficher
                'choice_value' => 'id', // Assurez-vous que 'id' est le nom du champ ID
                'placeholder' => 'Sélectionnez un jeu', // Optionnel : ajout d'une option de placeholder
            ])
            ->add('team1', EntityType::class, [
                'class' => 'App\Entity\Team',
                'choice_label' => 'team_name', // Assurez-vous que 'nom' est le nom du champ que vous souhaitez afficher
                'choice_value' => 'id', // Assurez-vous que 'id' est le nom du champ ID
                'placeholder' => 'Sélectionnez une équipe', // Optionnel : ajout d'une option de placeholder
            ])
            ->add('team2', EntityType::class, [
                'class' => 'App\Entity\Team',
                'choice_label' => 'team_name', // Assurez-vous que 'nom' est le nom du champ que vous souhaitez afficher
                'choice_value' => 'id', // Assurez-vous que 'id' est le nom du champ ID
                'placeholder' => 'Sélectionnez une équipe', // Optionnel : ajout d'une option de placeholder
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Versus::class,
        ]);
    }
}

src/Controller/VersusController.php
<?php

namespace App\Controller;

use App\Entity\Versus;
use App\Entity\Bet;
use App\Entity\Team;
use App\Form\VersusType;
use App\Repository\VersusRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/versus')]
class VersusController extends AbstractController
{
    #[Route('/', name: 'app_versus_index', methods: ['GET'])]
    public function index(VersusRepository $versusRepository): Response
    {
        return $this->render('versus/index.html.twig', [
            'versuses' => $versusRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_versus_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $versu = new Versus();
        $form = $this->createForm(VersusType::class, $versu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($versu);
            $entityManager->flush();

            return $this->redirectToRoute('app_versus_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('versus/new.html.twig', [
            'versu' => $versu,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_versus_show', methods: ['GET'])]
    public function show(Versus $versu): Response
    {
        return $this->render('versus/show.html.twig', [
            'versu' => $versu,
        ]);
    }

    #[Route('/{id}/valid', name: 'app_versus_valid', methods: ['GET'])]
    public function versusValid(Versus $versu, $id): Response
    {
        return $this->render('versus/valid.html.twig', [
            'versu' => $versu,
        ]);
    }

    #[Route('/{id}/validbet/{team}', name: 'app_versus_valid_bet', methods: ['GET'])]
    public function versusValidBet(Versus $versu, EntityManagerInterface $entityManager, $id, $team): Response
    {
        $winnerTeam = ($team == 'team1') ? $versu->getTeam1() : $versu->getTeam2();

        if ($winnerTeam instanceof Team) {
            $versu->setWinner($winnerTeam);

            $rate = ($team == 'team1') ? $versu->getRateTeam1() : $versu->getRateTeam2();

            $bets = $entityManager->getRepository(Bet::class)->findBy([
                'teamid' => $winnerTeam->getId(),
                'versusid' => $versu->getId(),
            ]);

            foreach ($bets as $bet) {
                $userBalanceUpdate = $bet->getAmount() * $rate;
                $bet->getUserid()->setBalance($bet->getUserid()->getBalance() + $userBalanceUpdate);
                $entityManager->persist($bet->getUserid());
            }

            $entityManager->flush();
        }

        return $this->redirectToRoute('app_versus_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/edit', name: 'app_versus_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Versus $versu, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VersusType::class, $versu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_versus_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('versus/edit.html.twig', [
            'versu' => $versu,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_versus_delete', methods: ['POST'])]
    public function delete(Request $request, Versus $versu, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$versu->getId(), $request->request->get('_token'))) {
            $entityManager->remove($versu);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_versus_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/versus/_delete_form.html.twig
<form method="post" action="{{ path('app_versus_delete', {'id': versu.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ versu.id) }}">
    <button class="btn">Delete</button>
</form>

templates/versus/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/versus/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Versus{% endblock %}

{% block body %}
    <h1>Edit Versus</h1>

    {{ include('versus/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_versus_index') }}">back to list</a>

    {{ include('versus/_delete_form.html.twig') }}
{% endblock %}

templates/versus/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paris{% endblock %}

{% block body %}

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_versus_new') }}">Créer un nouveau Pari !</a>
    {% endif %}

    <h1>Liste des Paris</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Equipe 1<th>
                <th>Cote Equipe 1</th>
                <th>Equipe 2<th>
                <th>Cote Equipe 2</th>
                <th>Description</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for versu in versuses %}
            <tr>
                <td>{{ versu.id }}</td>
                <td>{{ versu.team1.teamname }}</td>
                <td>{{ versu.rateTeam1 }}</td>
                <td>{{ versu.team2.teamname }}</td>
                <td>{{ versu.rateTeam2 }}</td>
                <td>{{ versu.description }}</td>
                <td>{{ versu.date ? versu.date|date('Y-m-d H:i:s') : '' }}</td>
                
                    <td>
                        <a href="{{ path('app_versus_show', {'id': versu.id}) }}">show</a>
                        {% if is_granted('ROLE_ADMIN') %}
                            {% if not versu.winner %}
                                <a href="{{ path('app_versus_edit', {'id': versu.id}) }}">edit</a>
                                <a href="{{ path('app_versus_valid', {'id': versu.id}) }}">Valider Pari</a>
                            {% endif %}
                        {% endif %}
                    </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/versus/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Versus{% endblock %}

{% block body %}
    <h1>Create new Versus</h1>

    {{ include('versus/_form.html.twig') }}

    <a href="{{ path('app_versus_index') }}">back to list</a>
{% endblock %}

templates/versus/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Versus{% endblock %}

{% block body %}
    <h1>Versus</h1>

    <table class="table">
        <tbody>
            {% if is_granted("ROLE_ADMIN") %}
            <tr>
                <th>Id</th>
                <td>{{ versu.id }}</td>
            </tr>
            {% endif %}
            <tr>
                <th>Description</th>
                <td>{{ versu.description }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ versu.date ? versu.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Equipe 1</th>
                <td>{{ versu.team1.teamname }}</td>
            </tr>
            <tr>
                <th>Rate_team1</th>
                <td>{{ versu.rateTeam1 }}</td>
            </tr>
            <tr>
                <th>Equipe 2</th>
                <td>{{ versu.team2.teamname }}</td>
            </tr>
            <tr>
                <th>Rate_team2</th>
                <td>{{ versu.rateTeam2 }}</td>
            </tr>
        </tbody>
    </table>

    {% if app.user %}
        {% set userHasBet = false %}
        {% set amount = null %}
        {% set teamBet = null %}
        {% for bet in app.user.bets %}
            {% if bet.versusid.id == versu.id %}
                {% set userHasBet = true %}
                {% set amount = bet.amount %}
                {% set teamBet = bet.teamid.teamname %}
            {% endif %}
        {% endfor %}
        {% if not userHasBet %}
            {% if is_granted('ROLE_ADMIN') %}
                    {% if not versu.winner %}
                        <a href="{{ path('app_versus_valid', {'id': versu.id}) }}">Valider Pari</a>
                        <a href="{{ path('app_versus_edit', {'id': versu.id}) }}">edit</a>
                        {{ include('versus/_delete_form.html.twig') }}
                    {% endif %}
            {% else %}
                <a href="{{ path('app_bet_new', {'id': versu.id}) }}">Parier</a>
            {% endif %}
        {% else %}
            <p>Vous avez déjà parier {{ amount|number_format(2, ',', '.') }} € sur {{ teamBet }}.</p>
        {% endif %}
    {% else %}
        <a href="{{ path('app_login') }}">Vous devez être connecter pour parier !</a>
    {% endif %}

    <a href="{{ path('app_versus_index') }}">back to list</a>

{% endblock %}

templates/versus/valid.html.twig
{% extends 'base.html.twig' %}

{% block title %}Versus{% endblock %}

{% block body %}
    <h1>Versus</h1>

    <table class="table">
        <tbody>
            {% if is_granted("ROLE_ADMIN") %}
            <tr>
                <th>Id</th>
                <td>{{ versu.id }}</td>
            </tr>
            {% endif %}
            <tr>
                <th>Description</th>
                <td>{{ versu.description }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ versu.date ? versu.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Equipe 1</th>
                <td>
                    {{ versu.team1.teamname }}
                    <a href="{{ path('app_versus_valid_bet', {'id': versu.id, 'team': 'team1'}) }}">Validez</a>
                </td>
            </tr>
            <tr>
                <th>Rate_team1</th>
                <td>{{ versu.rateTeam1 }}</td>
            </tr>
            <tr>
                <th>Equipe 2</th>
                <td>
                    {{ versu.team2.teamname }}
                    <a href="{{ path('app_versus_valid_bet', {'id': versu.id, 'team': 'team2'}) }}">Validez</a>
                </td>
            </tr>
            <tr>
                <th>Rate_team2</th>
                <td>{{ versu.rateTeam2 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_versus_index') }}">back to list</a>
{% endblock %}